/// All user-facing text lives here, keyed by language code.
/// Adding a language = adding one map (later: download it as a JSON pack).
/// Logic never compares against these strings.
class Strings {
  static const fallbackLanguage = 'en';

  /// True if [lang] (or the fallback) has text for [key].
  static bool has(String lang, String key) =>
      _packs[lang]?.containsKey(key) == true || _packs[fallbackLanguage]!.containsKey(key);

  static String of(String lang, String key) =>
      _packs[lang]?[key] ?? _packs[fallbackLanguage]![key] ?? key;

  /// Display text for a stored answer value ("yes" or a choice option id).
  static String answerLabel(String lang, String value) =>
      const ['yes', 'no', 'unsure'].contains(value) ? of(lang, value) : of(lang, 'opt_$value');

  /// BCP-47 locale for speech-to-text / text-to-speech engines.
  static const Map<String, String> speechLocales = {
    'hi': 'hi_IN',
    'en': 'en_IN',
  };

  static const Map<String, Map<String, String>> _packs = {
    'en': {
      'app_title': 'Health AI Assistant',
      'tagline': 'Offline • Local language • Human in control',
      'choose_language': 'Choose language',
      'continue': 'Continue',
      'change_language': 'Change language',
      'start': 'Start new consultation',
      'saved_count': 'Saved consultations',
      'pending_sync': 'Not yet sent',
      'new_consultation': 'New consultation',
      'describe_title': 'Describe what you see or hear',
      'describe_hint': 'e.g. "Child has fever for 3 days and cough"',
      'listening': 'Listening… tap again to stop',
      'mic_unavailable': 'Voice input not available on this phone. Please type.',
      'yes': 'Yes',
      'no': 'No',
      'unsure': 'Not sure',
      'summary_title': 'Consultation summary',
      'symptom_summary': 'Symptom summary',
      'suggestions_title': 'Possible next steps',
      'from_description': 'from description',
      'because': 'Because',
      'disclaimer':
          'This is only a suggestion, not a diagnosis. Please confirm with a clinician. The final decision is yours.',
      'confirm_save': 'I have reviewed this — save',
      'saved': 'Saved on this phone',
      'share_sms': 'Send summary by SMS',
      'finish': 'Finish & return home',
      'level_routine': 'Routine care',
      'level_clinicianReview': 'Clinician review needed',
      'level_urgentReferral': 'URGENT referral',

      'history': 'History',
      'no_history': 'No consultations saved yet.',
      'sent': 'Sent',
      'not_sent': 'Not sent',
      'details': 'Consultation details',
      'description': 'Description',

      'ai_title': 'Smart AI (offline)',
      'ai_subtitle':
          'A small AI model that understands the description better. Download once on Wi-Fi, then it works without internet. Rules and referrals are never decided by the AI.',
      'ai_use': 'Use smart AI',
      'ai_download': 'Download',
      'ai_cancel': 'Cancel',
      'ai_delete': 'Delete model',
      'ai_retry': 'Try again',
      'ai_status_unsupported': 'Not supported on this phone — keyword mode is used.',
      'ai_status_notDownloaded': 'Not downloaded',
      'ai_status_downloading': 'Downloading…',
      'ai_status_downloaded': 'Downloaded — ready offline',
      'ai_status_loading': 'Loading into memory…',
      'ai_status_ready': 'Ready',
      'ai_status_failed': 'Error',
      'ai_ram_warning': 'This phone may not have enough memory for this model.',
      'ai_phone_ram': 'Phone memory',
      'ai_keywords': 'Keyword mode',
      'ai_note':
          'Trained for this app on Hindi, Hinglish and English notes. About 280 MB; works on phones with 2 GB+ memory.',
      'ai_import': 'Import model file',
      'ai_import_hint':
          'No internet? Copy the .gguf file to this phone (USB cable, Bluetooth, SD card) and pick it here.',
      'ai_status_importing': 'Copying model…',
      'understanding': 'Understanding the description…',

      // Checks added at runtime
      'q_fever_stiff_neck': 'Is the neck stiff (cannot bend the chin to the chest)?',
      'q_fever_rash': 'Is there a rash all over the body (with red eyes or runny nose)?',
      'q_malaria_test': 'Was a malaria rapid test (RDT) done? What was the result?',
      'opt_rdt_positive': 'Positive',
      'opt_rdt_negative': 'Negative',
      'opt_rdt_not_done': 'Not done',
      'q_cough_fast_breathing':
          'Count breaths for one full minute. Is it fast? (2–12 months: 50 or more, 1–5 years: 40 or more, older: 30 or more)',
      'q_chest_indrawing': 'Does the lower chest pull in when breathing in (chest indrawing)?',
      'q_tb_symptoms': 'Is there weight loss, night sweats, or blood in the cough?',
      'q_dehyd_sunken_eyes': 'Are the eyes sunken?',
      'q_dehyd_thirsty': 'Is the patient very thirsty, drinking eagerly?',
      'q_dehyd_skin_pinch': 'Pinch the skin of the belly. How does it go back?',
      'opt_pinch_normal': 'Immediately',
      'opt_pinch_slow': 'Slowly',
      'opt_pinch_very_slow': 'Very slowly (2+ seconds)',
      'q_dehyd_restless': 'Is the patient restless or irritable?',
      'q_dehyd_thirsty_child': 'Is the child very thirsty, drinking eagerly?',
      'q_dehyd_restless_child': 'Is the child restless or irritable?',
      'because_cough_days': 'Since the cough is 2 weeks or longer, please check:',

      // Treatment / referral advice (rules, WHO IMCI)
      's_unsure_check': 'Some checks were "not sure". Please get a clinician to examine the patient.',
      's_stiff_neck': 'Fever with stiff neck: possible meningitis. Refer URGENTLY.',
      's_measles':
          'Fever with rash: possible measles. Keep away from other children, give vitamin A as per protocol, and get a clinician review.',
      's_malaria_positive':
          'Malaria test positive: start antimalarial treatment as per the national protocol (clinician to confirm the medicine and dose). Refer if any danger sign appears.',
      's_malaria_negative': 'Malaria test negative: look for other causes of the fever.',
      's_fever_care':
          'For high fever: paracetamol by weight as per protocol, sponge with lukewarm water, give plenty of fluids.',
      's_severe_pneumonia':
          'Chest indrawing: possible severe pneumonia. Refer URGENTLY; give the first antibiotic dose if your protocol allows.',
      's_infant_fast_breathing': 'Fast breathing in a baby under 2 months. Refer URGENTLY.',
      's_pneumonia':
          'Fast breathing: possible pneumonia. Oral amoxicillin as per your protocol (clinician to confirm the dose); follow up in 2–3 days.',
      's_cough_home':
          'Cough without fast breathing: likely a cough or cold. Warm fluids; honey only for children over 1 year. Return if breathing becomes fast or difficult.',
      's_severe_dehydration':
          'SEVERE dehydration. Refer URGENTLY; if the patient can drink, give ORS sips on the way.',
      's_some_dehydration':
          'Some dehydration: ORS Plan B — about 75 ml per kg over 4 hours at the health facility, then reassess. Zinc for children as per protocol.',

      // Chat consultation
      'note_added_fever': '+ Added {n} checks because of the fever',
      'note_added_cough': '+ Added {n} breathing checks because of the cough',
      'note_added_diarrhea': '+ Added {n} dehydration checks because of the loose motions',
      'note_added_cough_days': '+ Added a TB check because the cough is long',
      'note_skipped': '✓ Skipping {n} questions — already understood',
      'note_level': '⚠ Assessment changed: {level}',
      'note_advice': '💊 Advice updated: {text}',
      'assessment_title': 'Live assessment',
      'chat_start':
          'Tell me about the patient — what do you see or hear? Type, or tap the mic.',
      'chat_understood': 'From what you said, I understood:',
      'chat_understood_hint': 'Tap ✕ on anything that is wrong.',
      'chat_also_understood': 'Also noted:',
      'chat_nothing': "I couldn't pick out symptoms from that, so I'll ask step by step.",
      'chat_not_understood':
          "Sorry, I didn't get that. Tap one of the options below, or say it in other words.",
      'chat_removed': "Removed — I'll ask about it.",
      'chat_input_hint': 'Type your answer…',
      'chat_skip_describe': 'Skip — just ask me',
      'chat_done': 'Thank you. Preparing the summary…',
      'label_fever': 'Fever',
      'label_fever_days': 'Fever for',
      'label_cough': 'Cough',
      'label_cough_days': 'Cough for',
      'label_diarrhea': 'Loose motions',
      'label_blood_in_stool': 'Blood in stool',
      'ack_yes_1': 'Okay, noted.',
      'ack_yes_2': 'Understood.',
      'ack_no_1': 'Okay.',
      'ack_no_2': 'Alright.',
      'ack_unsure': "No problem, I'll keep that in mind.",
      'ack_choice': 'Thanks.',
      'ds_intro': 'Now a few important safety questions.',
      'qc_fever_days': 'You mentioned fever. For how many days has it been there?',
      'qc_cough_days': 'You mentioned a cough. For how long has it been there?',
      'qc_blood_in_stool': 'You mentioned loose motions. Is there any blood in the stool?',
      'because_fever': 'Since there is fever, please check:',
      'because_cough': 'Since there is a cough, please check:',
      'because_diarrhea': 'With loose motions, please check:',
      'q_ds_unconscious_child': 'Is the child unconscious, very drowsy or not responding?',
      'q_ds_convulsions_child': 'Has the child had fits (convulsions)?',
      'q_ds_cannot_drink_child': 'Is the child unable to drink or breastfeed?',
      'q_ds_vomits_everything_child': 'Does the child vomit everything they eat or drink?',
      'q_ds_breathing_child': "Is the child's breathing very difficult or very fast?",
      'q_fever_child': 'Does the child have fever?',
      'q_cough_child': 'Does the child have a cough?',
      'q_diarrhea_child': 'Does the child have loose motions?',

      // SMS conversation (feature phones)
      'sms_welcome': 'Health Assistant. Answer by number.',
      'sms_yes_no_help': '1=Yes 2=No 3=Not sure',
      'sms_invalid': 'Please reply with one of the numbers.',
      'sms_restart_hint': 'Send 0 to start again.',
      'sms_report_received': 'Report received. Ref:',

      // Questions
      'q_age_group': 'Age of the patient?',
      'opt_age_infant': 'Under 2 months',
      'opt_age_child': '2 months – 5 years',
      'opt_age_older': 'Over 5 years',
      'q_ds_unconscious': 'Is the patient unconscious, very drowsy or not responding?',
      'q_ds_convulsions': 'Has the patient had fits (convulsions)?',
      'q_ds_cannot_drink': 'Is the patient unable to drink anything (or baby unable to feed)?',
      'q_ds_vomits_everything': 'Does the patient vomit everything they eat or drink?',
      'q_ds_breathing': 'Is breathing very difficult or very fast?',
      'q_fever': 'Does the patient have fever?',
      'q_fever_days': 'For how many days has the fever been there?',
      'opt_d_1_2': '1–2 days',
      'opt_d_3_6': '3–6 days',
      'opt_d_7_plus': '7 days or more',
      'q_cough': 'Does the patient have a cough?',
      'q_cough_days': 'For how long has the cough been there?',
      'opt_c_lt_14': 'Less than 2 weeks',
      'opt_c_14_plus': '2 weeks or more',
      'q_diarrhea': 'Does the patient have loose motions (diarrhoea)?',
      'q_blood_in_stool': 'Is there blood in the stool?',

      // Suggestions
      's_urgent_danger':
          'Danger sign present. Refer urgently to the nearest higher facility (PHC/CHC/hospital). Arrange transport — do not delay.',
      's_infant_fever': 'Fever in a baby under 2 months can be serious. Refer urgently.',
      's_unsure_danger':
          'A danger sign could not be ruled out. Please get a clinician to examine the patient soon.',
      's_fever_long': 'Fever for 7 days or more. Refer for clinician evaluation.',
      's_fever_tests': 'If available: malaria rapid test (RDT) and temperature check.',
      's_cough_tb': 'Cough for 2 weeks or more. Refer for TB testing as per the local programme.',
      's_blood_stool': 'Blood in stool. Clinician review needed.',
      's_diarrhea_ors':
          'No dehydration: ORS Plan A at home — ORS after every loose stool, extra fluids, keep feeding; zinc for children for 10–14 days as per protocol.',
      's_common_checks':
          'Check temperature, breathing rate and oxygen level (if a pulse oximeter is available).',
      's_routine_observe':
          'No danger signs reported. Continue care here and advise the family to return if the patient gets worse.',
    },
    'hi': {
      'app_title': 'स्वास्थ्य AI सहायक',
      'tagline': 'ऑफ़लाइन • अपनी भाषा • फ़ैसला आपका',
      'choose_language': 'भाषा चुनें',
      'continue': 'आगे बढ़ें',
      'change_language': 'भाषा बदलें',
      'start': 'नई जाँच शुरू करें',
      'saved_count': 'सेव की गई जाँचें',
      'pending_sync': 'अभी भेजी नहीं गईं',
      'new_consultation': 'नई जाँच',
      'describe_title': 'जो दिख या सुनाई दे रहा है, बताइए',
      'describe_hint': 'जैसे: "बच्चे को 3 दिन से बुखार और खाँसी है"',
      'listening': 'सुन रहे हैं… रोकने के लिए फिर दबाएँ',
      'mic_unavailable': 'इस फ़ोन पर आवाज़ से लिखना उपलब्ध नहीं है। कृपया टाइप करें।',
      'yes': 'हाँ',
      'no': 'नहीं',
      'unsure': 'पक्का नहीं पता',
      'summary_title': 'जाँच का सारांश',
      'symptom_summary': 'लक्षणों का सारांश',
      'suggestions_title': 'आगे क्या कर सकते हैं',
      'from_description': 'विवरण से',
      'because': 'कारण',
      'disclaimer':
          'यह सिर्फ़ सुझाव है, निदान नहीं। कृपया डॉक्टर/क्लिनिशियन से पुष्टि करें। अंतिम फ़ैसला आपका है।',
      'confirm_save': 'मैंने देख लिया है — सेव करें',
      'saved': 'इस फ़ोन में सेव हो गया',
      'share_sms': 'SMS से सारांश भेजें',
      'finish': 'पूरा करें और होम पर जाएँ',
      'level_routine': 'सामान्य देखभाल',
      'level_clinicianReview': 'डॉक्टर से जाँच ज़रूरी',
      'level_urgentReferral': 'तुरंत रेफ़र करें',

      'history': 'पिछली जाँचें',
      'no_history': 'अभी तक कोई जाँच सेव नहीं हुई।',
      'sent': 'भेजा गया',
      'not_sent': 'नहीं भेजा',
      'details': 'जाँच का विवरण',
      'description': 'विवरण',

      'ai_title': 'स्मार्ट AI (ऑफ़लाइन)',
      'ai_subtitle':
          'एक छोटा AI मॉडल जो विवरण को बेहतर समझता है। एक बार Wi-Fi पर डाउनलोड करें, फिर बिना इंटरनेट के चलता है। रेफ़रल का फ़ैसला AI कभी नहीं करता।',
      'ai_use': 'स्मार्ट AI इस्तेमाल करें',
      'ai_download': 'डाउनलोड करें',
      'ai_cancel': 'रद्द करें',
      'ai_delete': 'मॉडल हटाएँ',
      'ai_retry': 'फिर से कोशिश करें',
      'ai_status_unsupported': 'इस फ़ोन पर उपलब्ध नहीं — कीवर्ड मोड चलेगा।',
      'ai_status_notDownloaded': 'डाउनलोड नहीं हुआ',
      'ai_status_downloading': 'डाउनलोड हो रहा है…',
      'ai_status_downloaded': 'डाउनलोड हो गया — ऑफ़लाइन तैयार',
      'ai_status_loading': 'मेमोरी में लोड हो रहा है…',
      'ai_status_ready': 'तैयार',
      'ai_status_failed': 'गड़बड़ी',
      'ai_ram_warning': 'इस फ़ोन में इस मॉडल के लिए शायद पर्याप्त मेमोरी नहीं है।',
      'ai_phone_ram': 'फ़ोन की मेमोरी',
      'ai_keywords': 'कीवर्ड मोड',
      'ai_note':
          'इस ऐप के लिए हिंदी, हिंग्लिश और अंग्रेज़ी नोट्स पर ट्रेन किया गया। लगभग 280 MB; 2 GB+ मेमोरी वाले फ़ोन पर चलता है।',
      'ai_import': 'मॉडल फ़ाइल चुनें',
      'ai_import_hint':
          'इंटरनेट नहीं है? .gguf फ़ाइल को USB, ब्लूटूथ या SD कार्ड से इस फ़ोन में कॉपी करें और यहाँ चुनें।',
      'ai_status_importing': 'मॉडल कॉपी हो रहा है…',
      'understanding': 'विवरण समझ रहे हैं…',

      'q_fever_stiff_neck': 'क्या गर्दन अकड़ी हुई है (ठुड्डी छाती तक नहीं झुकती)?',
      'q_fever_rash': 'क्या पूरे शरीर पर दाने हैं (लाल आँखें या नाक बहने के साथ)?',
      'q_malaria_test': 'क्या मलेरिया रैपिड टेस्ट (RDT) हुआ? नतीजा क्या था?',
      'opt_rdt_positive': 'पॉज़िटिव',
      'opt_rdt_negative': 'नेगेटिव',
      'opt_rdt_not_done': 'नहीं हुआ',
      'q_cough_fast_breathing':
          'एक पूरे मिनट साँसें गिनें। क्या साँस तेज़ है? (2–12 महीने: 50 या ज़्यादा, 1–5 साल: 40 या ज़्यादा, बड़े: 30 या ज़्यादा)',
      'q_chest_indrawing': 'क्या साँस लेते समय छाती का निचला हिस्सा अंदर धँसता है?',
      'q_tb_symptoms': 'क्या वज़न घटा है, रात को पसीना आता है, या खाँसी में खून आता है?',
      'q_dehyd_sunken_eyes': 'क्या आँखें धँसी हुई हैं?',
      'q_dehyd_thirsty': 'क्या मरीज़ को बहुत प्यास लग रही है, जल्दी-जल्दी पी रहा है?',
      'q_dehyd_skin_pinch': 'पेट की त्वचा को चुटकी से उठाएँ। वह कैसे वापस जाती है?',
      'opt_pinch_normal': 'तुरंत',
      'opt_pinch_slow': 'धीरे',
      'opt_pinch_very_slow': 'बहुत धीरे (2+ सेकंड)',
      'q_dehyd_restless': 'क्या मरीज़ बेचैन या चिड़चिड़ा है?',
      'q_dehyd_thirsty_child': 'क्या बच्चे को बहुत प्यास लग रही है, जल्दी-जल्दी पी रहा है?',
      'q_dehyd_restless_child': 'क्या बच्चा बेचैन या चिड़चिड़ा है?',
      'because_cough_days': 'खाँसी 2 हफ़्ते या ज़्यादा से है, इसलिए यह देखना ज़रूरी है:',

      's_unsure_check': 'कुछ जाँचों का जवाब "पक्का नहीं" था। कृपया डॉक्टर से मरीज़ की जाँच करवाएँ।',
      's_stiff_neck': 'बुखार के साथ गर्दन अकड़ी है: मेनिनजाइटिस हो सकता है। तुरंत रेफ़र करें।',
      's_measles':
          'बुखार के साथ दाने: खसरा हो सकता है। दूसरे बच्चों से दूर रखें, प्रोटोकॉल के अनुसार विटामिन A दें, और डॉक्टर से जाँच करवाएँ।',
      's_malaria_positive':
          'मलेरिया टेस्ट पॉज़िटिव: राष्ट्रीय प्रोटोकॉल के अनुसार मलेरिया की दवा शुरू करें (दवा और खुराक डॉक्टर से पक्की करें)। खतरे का कोई लक्षण दिखे तो रेफ़र करें।',
      's_malaria_negative': 'मलेरिया टेस्ट नेगेटिव: बुखार के दूसरे कारण देखें।',
      's_fever_care':
          'तेज़ बुखार में: प्रोटोकॉल के अनुसार वज़न से पैरासिटामोल, गुनगुने पानी से पोंछें, खूब तरल दें।',
      's_severe_pneumonia':
          'छाती धँसना: गंभीर निमोनिया हो सकता है। तुरंत रेफ़र करें; प्रोटोकॉल अनुमति दे तो एंटीबायोटिक की पहली खुराक दें।',
      's_infant_fast_breathing': '2 महीने से छोटे बच्चे की साँस तेज़ है। तुरंत रेफ़र करें।',
      's_pneumonia':
          'तेज़ साँस: निमोनिया हो सकता है। प्रोटोकॉल के अनुसार अमोक्सिसिलिन (खुराक डॉक्टर से पक्की करें); 2–3 दिन में दोबारा देखें।',
      's_cough_home':
          'तेज़ साँस के बिना खाँसी: शायद सर्दी-खाँसी है। गुनगुना पानी दें; शहद सिर्फ़ 1 साल से बड़े बच्चों को। साँस तेज़ या मुश्किल हो तो वापस आएँ।',
      's_severe_dehydration':
          'गंभीर पानी की कमी। तुरंत रेफ़र करें; मरीज़ पी सके तो रास्ते में घूँट-घूँट ORS दें।',
      's_some_dehydration':
          'कुछ पानी की कमी: ORS प्लान B — स्वास्थ्य केंद्र पर 4 घंटे में लगभग 75 ml प्रति किलो, फिर दोबारा जाँचें। बच्चों को प्रोटोकॉल के अनुसार ज़िंक।',
      'note_added_fever': '+ बुखार की वजह से {n} जाँचें जोड़ी गईं',
      'note_added_cough': '+ खाँसी की वजह से साँस की {n} जाँचें जोड़ी गईं',
      'note_added_diarrhea': '+ दस्त की वजह से पानी की कमी की {n} जाँचें जोड़ी गईं',
      'note_added_cough_days': '+ लंबी खाँसी की वजह से TB की जाँच जोड़ी गई',
      'note_skipped': '✓ {n} सवाल छोड़े — पहले ही समझ आ गए',
      'note_level': '⚠ आकलन बदला: {level}',
      'note_advice': '💊 सलाह बदली: {text}',
      'assessment_title': 'लाइव आकलन',
      'chat_start': 'मरीज़ के बारे में बताइए — क्या दिख या सुनाई दे रहा है? लिखें या माइक दबाएँ।',
      'chat_understood': 'आपकी बात से यह समझ आया:',
      'chat_understood_hint': 'जो गलत हो उस पर ✕ दबाएँ।',
      'chat_also_understood': 'यह भी नोट किया:',
      'chat_nothing': 'इससे लक्षण समझ नहीं आए, इसलिए एक-एक करके पूछते हैं।',
      'chat_not_understood': 'माफ़ कीजिए, समझ नहीं आया। नीचे कोई विकल्प दबाएँ या दूसरे शब्दों में बताएँ।',
      'chat_removed': 'हटा दिया — इसके बारे में सवाल पूछा जाएगा।',
      'chat_input_hint': 'अपना जवाब लिखें…',
      'chat_skip_describe': 'छोड़ें — सीधे सवाल पूछें',
      'chat_done': 'धन्यवाद। सारांश तैयार हो रहा है…',
      'label_fever': 'बुखार',
      'label_fever_days': 'बुखार कब से',
      'label_cough': 'खाँसी',
      'label_cough_days': 'खाँसी कब से',
      'label_diarrhea': 'दस्त',
      'label_blood_in_stool': 'मल में खून',
      'ack_yes_1': 'ठीक है, नोट कर लिया।',
      'ack_yes_2': 'समझ गए।',
      'ack_no_1': 'ठीक है।',
      'ack_no_2': 'अच्छा।',
      'ack_unsure': 'कोई बात नहीं, इसका ध्यान रखेंगे।',
      'ack_choice': 'धन्यवाद।',
      'ds_intro': 'अब कुछ ज़रूरी सुरक्षा सवाल।',
      'qc_fever_days': 'आपने बुखार बताया। कितने दिन से है?',
      'qc_cough_days': 'आपने खाँसी बताई। कब से है?',
      'qc_blood_in_stool': 'आपने दस्त बताए। क्या मल में खून आ रहा है?',
      'because_fever': 'बुखार है, इसलिए यह देखना ज़रूरी है:',
      'because_cough': 'खाँसी है, इसलिए यह देखना ज़रूरी है:',
      'because_diarrhea': 'दस्त हैं, इसलिए यह देखना ज़रूरी है:',
      'q_ds_unconscious_child': 'क्या बच्चा बेहोश है, बहुत सुस्त है या जवाब नहीं दे रहा?',
      'q_ds_convulsions_child': 'क्या बच्चे को दौरे (झटके) आए हैं?',
      'q_ds_cannot_drink_child': 'क्या बच्चा कुछ पी नहीं पा रहा या माँ का दूध नहीं पी रहा?',
      'q_ds_vomits_everything_child': 'क्या बच्चा जो भी खाता-पीता है, सब उल्टी कर देता है?',
      'q_ds_breathing_child': 'क्या बच्चे को साँस लेने में बहुत तकलीफ़ है या साँस बहुत तेज़ है?',
      'q_fever_child': 'क्या बच्चे को बुखार है?',
      'q_cough_child': 'क्या बच्चे को खाँसी है?',
      'q_diarrhea_child': 'क्या बच्चे को दस्त हो रहे हैं?',

      'sms_welcome': 'स्वास्थ्य सहायक। नंबर से जवाब दें।',
      'sms_yes_no_help': '1=हाँ 2=नहीं 3=पक्का नहीं',
      'sms_invalid': 'कृपया दिए गए नंबरों में से एक भेजें।',
      'sms_restart_hint': 'फिर से शुरू करने के लिए 0 भेजें।',
      'sms_report_received': 'रिपोर्ट मिल गई। Ref:',

      'q_age_group': 'मरीज़ की उम्र?',
      'opt_age_infant': '2 महीने से कम',
      'opt_age_child': '2 महीने – 5 साल',
      'opt_age_older': '5 साल से ज़्यादा',
      'q_ds_unconscious': 'क्या मरीज़ बेहोश है, बहुत सुस्त है या जवाब नहीं दे रहा?',
      'q_ds_convulsions': 'क्या मरीज़ को दौरे (झटके) आए हैं?',
      'q_ds_cannot_drink': 'क्या मरीज़ कुछ भी पी नहीं पा रहा (या बच्चा दूध नहीं पी रहा)?',
      'q_ds_vomits_everything': 'क्या मरीज़ जो भी खाता-पीता है, सब उल्टी कर देता है?',
      'q_ds_breathing': 'क्या साँस लेने में बहुत तकलीफ़ है या साँस बहुत तेज़ चल रही है?',
      'q_fever': 'क्या मरीज़ को बुखार है?',
      'q_fever_days': 'बुखार कितने दिन से है?',
      'opt_d_1_2': '1–2 दिन',
      'opt_d_3_6': '3–6 दिन',
      'opt_d_7_plus': '7 दिन या ज़्यादा',
      'q_cough': 'क्या खाँसी है?',
      'q_cough_days': 'खाँसी कब से है?',
      'opt_c_lt_14': '2 हफ़्ते से कम',
      'opt_c_14_plus': '2 हफ़्ते या ज़्यादा',
      'q_diarrhea': 'क्या दस्त (लूज़ मोशन) हो रहे हैं?',
      'q_blood_in_stool': 'क्या मल में खून आ रहा है?',

      's_urgent_danger':
          'खतरे का लक्षण है। तुरंत नज़दीकी बड़े अस्पताल (PHC/CHC) रेफ़र करें। गाड़ी का इंतज़ाम करें — देर न करें।',
      's_infant_fever': '2 महीने से छोटे बच्चे में बुखार गंभीर हो सकता है। तुरंत रेफ़र करें।',
      's_unsure_danger': 'खतरे के लक्षण से इनकार नहीं किया जा सका। जल्दी किसी डॉक्टर से जाँच करवाएँ।',
      's_fever_long': '7 दिन या ज़्यादा से बुखार है। डॉक्टर के पास जाँच के लिए भेजें।',
      's_fever_tests': 'अगर उपलब्ध हो: मलेरिया रैपिड टेस्ट (RDT) और तापमान जाँच।',
      's_cough_tb': '2 हफ़्ते या ज़्यादा से खाँसी है। स्थानीय कार्यक्रम के अनुसार TB जाँच के लिए भेजें।',
      's_blood_stool': 'मल में खून है। डॉक्टर से जाँच ज़रूरी है।',
      's_diarrhea_ors':
          'पानी की कमी नहीं: घर पर ORS प्लान A — हर दस्त के बाद ORS, ज़्यादा तरल, खाना जारी रखें; बच्चों को प्रोटोकॉल के अनुसार 10–14 दिन ज़िंक।',
      's_common_checks': 'तापमान, साँस की गति और ऑक्सीजन (अगर पल्स ऑक्सीमीटर हो) जाँचें।',
      's_routine_observe':
          'कोई खतरे का लक्षण नहीं बताया गया। यहीं देखभाल जारी रखें और हालत बिगड़ने पर वापस आने को कहें।',
    },
  };
}
